Fullpipe\BannerBundle\Entity\Banner:
    type: entity
    table: fp_banner
    repositoryClass: Fullpipe\BannerBundle\Entity\BannerRepository
    fields:
        name:
            type: string
            length: 255
        url:
            type: text
        html:
            type: text
            nullable: true
        position:
            type: integer
        startsAt:
            type: datetime
            nullable: true
            column: starts_at
        endsAt:
            type: datetime
            nullable: true
            column: ends_at
    manyToOne:
        place:
            targetEntity: Fullpipe\BannerBundle\Entity\Place
            inversedBy: banners
            joinColumn:
                name: place_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
