Fullpipe\BannerBundle\Entity\Banner:
    type: entity
    table: fp_banner
    repositoryClass: Fullpipe\BannerBundle\Entity\BannerRepository
    fields:
        name:
            type: string
            length: 255
        place:
            type: string
            length: 255
        url:
            type: text
        html:
            type: text
            nullable: true
        startsAt:
            type: datetime
            nullable: true
        endsAt:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
