fullpipe_sylius_backend_banner_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: fullpipe.controller.banner:indexAction
        _sylius:
            template: FullpipeBannerBundle:Sylius/Backend/Banner:index.html.twig

fullpipe_sylius_backend_banner_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: fullpipe.controller.banner:createAction
        _sylius:
            redirect: fullpipe_sylius_backend_banner_index
            form: fullpipe_banner_banner
            template: FullpipeBannerBundle:Sylius/Backend/Banner:create.html.twig

fullpipe_sylius_backend_banner_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: fullpipe.controller.banner:updateAction
        _sylius:
            redirect: fullpipe_sylius_backend_banner_index
            form: fullpipe_banner_banner
            template: FullpipeBannerBundle:Sylius/Backend/Banner:update.html.twig

fullpipe_sylius_backend_banner_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: fullpipe.controller.banner:deleteAction
        _sylius:
            redirect: fullpipe_sylius_backend_banner_index
